version: '3'
services:
  app:
    build: docker/app
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
    tty: true
    environment:
      - "DSN=postgres://user1:password@database:5432/testdb?sslmode=disable"
    links:
      - db:database

  db:
    build: docker/db
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=user1"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=testdb"

