version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
    tty: true
    environment:
      - "DSN=root:password@postgres:5432/testdb?sslmode=disable"
    links:
      - db

  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    tty: true
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=password"

